/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    listings: Listing;
    testimonials: Testimonial;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'hero-section': HeroSection;
    'renovation-section': RenovationSection;
    'about-section': AboutSection;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'hero-section': HeroSectionSelect<false> | HeroSectionSelect<true>;
    'renovation-section': RenovationSectionSelect<false> | RenovationSectionSelect<true>;
    'about-section': AboutSectionSelect<false> | AboutSectionSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins can manage other users. Editors can edit all site content but cannot manage user accounts.
   */
  roles: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and SEO, e.g. "Front exterior of 123 Main St".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Properties shown in the "For Sale" / "Recently Sold" tabs. Mark exactly one as Featured to show it on the homepage hero.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  _order?: string | null;
  status: 'for_sale' | 'sold';
  /**
   * Shows this listing in the homepage hero as the featured property. Only one listing should be featured at a time — marking a new one automatically un-marks the previous one.
   */
  featured?: boolean | null;
  photo: number | Media;
  /**
   * Small tag shown on the photo, e.g. "27 Days on Market", "Price Cut $25K", "Open Fri 4–6pm", "Sold".
   */
  badgeText: string;
  badgeStyle: 'dark' | 'accent' | 'outline';
  /**
   * Dollar amount, no commas or symbols, e.g. 1299000.
   */
  price: number;
  /**
   * Full display address as one line, e.g. "18147 Gallineta St, Rowland Heights, CA".
   */
  address: string;
  beds?: number | null;
  baths?: number | null;
  sqft?: number | null;
  representationType?: ('buyer' | 'seller') | null;
  /**
   * Free text, e.g. "30 days ago", "3 months ago".
   */
  soldTimeAgoLabel?: string | null;
  /**
   * Optional link to the full listing detail page (MLS/IDX), once available.
   */
  externalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client reviews. Check "Featured on Homepage" to show a testimonial in the About section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  _order?: string | null;
  quote: string;
  authorName: string;
  /**
   * e.g. "Jurupa Valley, CA"
   */
  location: string;
  rating: number;
  featuredOnHomepage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  _order?: T;
  status?: T;
  featured?: T;
  photo?: T;
  badgeText?: T;
  badgeStyle?: T;
  price?: T;
  address?: T;
  beds?: T;
  baths?: T;
  sqft?: T;
  representationType?: T;
  soldTimeAgoLabel?: T;
  externalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  _order?: T;
  quote?: T;
  authorName?: T;
  location?: T;
  rating?: T;
  featuredOnHomepage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Branding, navigation, footer, contact info, and service areas shown across the whole site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  brandSubline: string;
  favicon?: (number | null) | Media;
  ogImage?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  headerCtaLabel: string;
  headerCtaHref: string;
  phone: string;
  email: string;
  officeAddress: string;
  serviceAreas?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'linkedin' | 'instagram' | 'other';
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  copyrightLine: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The top banner of the homepage, including the headline, search bar note, and stat tiles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section".
 */
export interface HeroSection {
  id: number;
  eyebrowText: string;
  /**
   * Text before the emphasized phrase.
   */
  headlinePre?: string | null;
  /**
   * The emphasized (highlighted) phrase.
   */
  headlineEmphasis: string;
  /**
   * Text after the emphasized phrase.
   */
  headlinePost?: string | null;
  leadParagraph: string;
  primaryCtaLabel: string;
  primaryCtaHref: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
  /**
   * Small note under the search bar, e.g. explaining IDX search is coming soon.
   */
  searchBarNote?: string | null;
  /**
   * Exactly 4 stat tiles, e.g. "87" / "Homes Sold".
   */
  stats?:
    | {
        number: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The "Renovation & Distressed Property Experts" section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "renovation-section".
 */
export interface RenovationSection {
  id: number;
  kicker: string;
  heading: string;
  intro: string;
  /**
   * 3 feature blocks recommended.
   */
  features?:
    | {
        icon: 'wrench' | 'house' | 'blueprint' | 'hammer' | 'dollar' | 'checklist' | 'key';
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Before/after, photo, or video tiles for the renovation gallery. Add, remove, or reorder freely.
   */
  galleryTiles?:
    | (
        | {
            beforeImage: number | Media;
            afterImage: number | Media;
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'beforeAfterTile';
          }
        | {
            image: number | Media;
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'photoTile';
          }
        | {
            sourceType: 'url' | 'upload';
            /**
             * YouTube or Vimeo link.
             */
            videoUrl?: string | null;
            videoFile?: (number | null) | Media;
            title: string;
            subtitle?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoTile';
          }
      )[]
    | null;
  /**
   * Small italic note under the gallery, e.g. flagging placeholder content.
   */
  note?: string | null;
  bannerHeading: string;
  bannerText: string;
  bannerCtaLabel: string;
  bannerCtaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Agent bio, photo, and specialties shown in the "Meet Your Agent" section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section".
 */
export interface AboutSection {
  id: number;
  photo: number | Media;
  rating: number;
  reviewCount: number;
  kicker: string;
  name: string;
  bio: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Chips shown under the bio, e.g. "Buyer's Agent", "Listing Agent".
   */
  specialties?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language: string;
        id?: string | null;
      }[]
    | null;
  brokerage: string;
  brokerageLocation: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandSubline?: T;
  favicon?: T;
  ogImage?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  headerCtaLabel?: T;
  headerCtaHref?: T;
  phone?: T;
  email?: T;
  officeAddress?: T;
  serviceAreas?:
    | T
    | {
        area?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  copyrightLine?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-section_select".
 */
export interface HeroSectionSelect<T extends boolean = true> {
  eyebrowText?: T;
  headlinePre?: T;
  headlineEmphasis?: T;
  headlinePost?: T;
  leadParagraph?: T;
  primaryCtaLabel?: T;
  primaryCtaHref?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  searchBarNote?: T;
  stats?:
    | T
    | {
        number?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "renovation-section_select".
 */
export interface RenovationSectionSelect<T extends boolean = true> {
  kicker?: T;
  heading?: T;
  intro?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  galleryTiles?:
    | T
    | {
        beforeAfterTile?:
          | T
          | {
              beforeImage?: T;
              afterImage?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        photoTile?:
          | T
          | {
              image?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
        videoTile?:
          | T
          | {
              sourceType?: T;
              videoUrl?: T;
              videoFile?: T;
              title?: T;
              subtitle?: T;
              id?: T;
              blockName?: T;
            };
      };
  note?: T;
  bannerHeading?: T;
  bannerText?: T;
  bannerCtaLabel?: T;
  bannerCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-section_select".
 */
export interface AboutSectionSelect<T extends boolean = true> {
  photo?: T;
  rating?: T;
  reviewCount?: T;
  kicker?: T;
  name?: T;
  bio?: T;
  specialties?:
    | T
    | {
        label?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  brokerage?: T;
  brokerageLocation?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}